<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Cant. find &quot;trino&quot; from new data source modal UI</title>
    <link>https://discuss.redash.io/t/cant-find-trino-from-new-data-source-modal-ui/9919</link>
    <description>Tried to add Trino data source from re:dash(v10.1.0) UI

trino python package and others are set as it should be. However, I can&#39;t find trino 


redash ver: v10.1.0</description>
    
    <lastBuildDate>Tue, 01 Feb 2022 15:32:08 +0000</lastBuildDate>
    <category>Usage Support</category>
    <atom:link href="https://discuss.redash.io/t/cant-find-trino-from-new-data-source-modal-ui/9919.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Cant. find &quot;trino&quot; from new data source modal UI</title>
        <dc:creator><![CDATA[jesse]]></dc:creator>
        <description><![CDATA[
            <p>The Trino query runner will not be enabled if it encounters an error during its initialisation.</p>
<p>If you remove the <code>try...except</code> block on the query runner you will be able to see the exception in your Redash logs:</p>
<aside class="onebox githubblob" data-onebox-src="https://github.com/getredash/redash/blob/26ac8ab1cd56f550bef400d2db6e58f87ed2ec45/redash/query_runner/trino.py#L8-L14">
  <header class="source">

      <a href="https://github.com/getredash/redash/blob/26ac8ab1cd56f550bef400d2db6e58f87ed2ec45/redash/query_runner/trino.py#L8-L14" target="_blank" rel="noopener">github.com</a>
  </header>

  <article class="onebox-body">
    <h4><a href="https://github.com/getredash/redash/blob/26ac8ab1cd56f550bef400d2db6e58f87ed2ec45/redash/query_runner/trino.py#L8-L14" target="_blank" rel="noopener">getredash/redash/blob/26ac8ab1cd56f550bef400d2db6e58f87ed2ec45/redash/query_runner/trino.py#L8-L14</a></h4>



    <pre class="onebox">      <code class="lang-py">
        <ol class="start lines" start="8" style="counter-reset: li-counter 7 ;">
            <li>try:</li>
            <li>    import trino</li>
            <li>    from trino.exceptions import DatabaseError</li>
            <li>
            </li>
<li>    enabled = True</li>
            <li>except ImportError:</li>
            <li>    enabled = False</li>
        </ol>
      </code>
    </pre>



  </article>

  <div class="onebox-metadata">
    
    
  </div>

  <div style="clear: both"></div>
</aside>

          <p><a href="https://discuss.redash.io/t/cant-find-trino-from-new-data-source-modal-ui/9919/2">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/cant-find-trino-from-new-data-source-modal-ui/9919/2</link>
        <pubDate>Tue, 01 Feb 2022 15:32:08 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-9919-2</guid>
        <source url="https://discuss.redash.io/t/cant-find-trino-from-new-data-source-modal-ui/9919.rss">Cant. find &quot;trino&quot; from new data source modal UI</source>
      </item>
      <item>
        <title>Cant. find &quot;trino&quot; from new data source modal UI</title>
        <dc:creator><![CDATA[Daniel_Park]]></dc:creator>
        <description><![CDATA[
            <p>Tried to add Trino data source from re:dash(v10.1.0) UI</p>
<p>trino python package and others are set as it should be. However, I canâ€™t find trino</p>
<p>redash ver: v10.1.0</p>
          <p><a href="https://discuss.redash.io/t/cant-find-trino-from-new-data-source-modal-ui/9919/1">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/cant-find-trino-from-new-data-source-modal-ui/9919/1</link>
        <pubDate>Thu, 27 Jan 2022 09:08:18 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-9919-1</guid>
        <source url="https://discuss.redash.io/t/cant-find-trino-from-new-data-source-modal-ui/9919.rss">Cant. find &quot;trino&quot; from new data source modal UI</source>
      </item>
  </channel>
</rss>
