<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>Redashv8 cant connect to mysql8</title>
    <link>https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943</link>
    <description>Hi ,

i have use RedashV8 on premise install via docker on  Ubuntu 18.04.4 and it works very good with mysqlv5 
We have to upgrade mysql to V8 and we start to see issues with the connection 
it return
&quot;Connection Test Failed:
(2059, &#39;Plugin caching_sha2_password could not be loaded: /usr/lib/x86_64-linux-gnu/mariadb19/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory&#39;&quot;

i saw these two discuss
http://discuss.redash.io/t/cant-connect-mysql-to-redash-v8/6328
http://discuss.redash.io/t/connection-test-failed-mysql/4118

and i have add 
MYSQL_DEFAULT_AUTH=mysql_native_password to env 
but it is also do not solve the issue 

do you have another suggestion at the client side and not change the password plugin at the mysql side ?</description>
    
    <lastBuildDate>Wed, 25 Aug 2021 07:03:12 +0000</lastBuildDate>
    <category>Self Hosted Redash Support</category>
    <atom:link href="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943.rss" rel="self" type="application/rss+xml" />
      <item>
        <title>Redashv8 cant connect to mysql8</title>
        <dc:creator><![CDATA[hananv]]></dc:creator>
        <description><![CDATA[
            <p>and the story continue <img src="https://emoji.discourse-cdn.com/twitter/slight_smile.png?v=10" title=":slight_smile:" class="emoji" alt=":slight_smile:"></p>
<p>i tried to work with the instruction and do<br>
sudo apt-get update but it doesnt work with this error</p>
<p>"Ign:1 <a href="http://deb.debian.org/debian" class="inline-onebox" rel="noopener nofollow ugc">Index of /debian</a> buster InRelease<br>
Ign:2 <a href="http://deb.debian.org/debian" class="inline-onebox" rel="noopener nofollow ugc">Index of /debian</a> buster-updates InRelease<br>
Err:3 <a href="http://deb.debian.org/debian" class="inline-onebox" rel="noopener nofollow ugc">Index of /debian</a> buster Release<br>
404  Not Found [IP: 199.232.138.132 80]<br>
Err:4 <a href="http://deb.debian.org/debian" class="inline-onebox" rel="noopener nofollow ugc">Index of /debian</a> buster-updates Release<br>
404  Not Found [IP: 199.232.138.132 80]<br>
Ign:5 <a href="http://security.debian.org/debian-security" class="inline-onebox" rel="noopener nofollow ugc">Index of /debian-security</a> buster/updates InRelease<br>
Err:6 <a href="http://security.debian.org/debian-security" class="inline-onebox" rel="noopener nofollow ugc">Index of /debian-security</a> buster/updates Release<br>
404  Not Found [IP: 199.232.138.132 80]<br>
Hit:7 <a href="https://packages.microsoft.com/debian/10/prod" class="inline-onebox" rel="noopener nofollow ugc">Index of /debian/10/prod/</a> buster InRelease<br>
Reading package lists… Done<br>
E: The repository ‘<a href="http://deb.debian.org/debian" class="inline-onebox" rel="noopener nofollow ugc">Index of /debian</a> buster Release’ no longer has a Release file.<br>
N: Updating from such a repository can’t be done securely, and is therefore disabled by default.<br>
N: See apt-secure(8) manpage for repository creation and user configuration details.<br>
E: The repository ‘<a href="http://deb.debian.org/debian" class="inline-onebox" rel="noopener nofollow ugc">Index of /debian</a> buster-updates Release’ no longer has a Release file.<br>
N: Updating from such a repository can’t be done securely, and is therefore disabled by default.<br>
N: See apt-secure(8) manpage for repository creation and user configuration details.<br>
E: The repository ‘<a href="http://security.debian.org/debian-security" class="inline-onebox" rel="noopener nofollow ugc">Index of /debian-security</a> buster/updates Release’ no longer has a Release file.<br>
N: Updating from such a repository can’t be done securely, and is therefore disabled by default.<br>
N: See apt-secure(8) manpage for repository creation and user configuration details<br>
"</p>
<p>the problem is that http is not valid any more and you need to change to https<br>
so you need to edit /etc/apt/sources.list and change to http to https<br>
(i didnt find how to edit it at the docker so i cp the file to my linux edit it there and recopy to docker<br>
example docker cp  ./source.list 3cd1f91a2184:/etc/apt/sources.list<br>
)<br>
then<br>
sudo apt-get update<br>
success !</p>
<p>next i try<br>
sudo apt-get install libmysqlclient-dev<br>
but it fail and suggest to use</p>
<p>“However the following packages replace it:<br>
libmariadb-dev-compat libmariadb-dev”</p>
<p>so i use<br>
sudo apt-get install libmariadb-dev</p>
<p>i update it on<br>
redash_worker_1<br>
redash_adhoc_worker_1<br>
redash_scheduled_worker_1<br>
redash_scheduler_1</p>
<p>and test connect to DB and query works !</p>
<p>however the story do not end here …<br>
i try to connect to another DB also mysqlv8 and i now get new issue<br>
“RSA Encryption not supported - caching_sha2_password plugin was built with GnuTLS support”<br>
i tried to update now gnutls-bin<br>
sudo apt install gnutls-bin</p>
<p>but it still have the problem</p>
          <p><a href="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/10">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/10</link>
        <pubDate>Wed, 25 Aug 2021 07:03:12 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-8943-10</guid>
        <source url="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943.rss">Redashv8 cant connect to mysql8</source>
      </item>
      <item>
        <title>Redashv8 cant connect to mysql8</title>
        <dc:creator><![CDATA[jesse]]></dc:creator>
        <description><![CDATA[
            <p>Good research! Did you try the suggestion from the issue you linked?</p>
<p>quoting:</p>
<blockquote>
<p>This is now resolved.</p>
<p>After some time, I attempted to use the <code>caching_sha2_password</code> plugin again. I encountered the following error:</p>
<pre><code class="lang-auto">RSA Encryption not supported - caching_sha2_password plugin was built with GnuTLS support
</code></pre>
<p>Which prompted me to install <code>gnutls-bin</code> , which did the trick.</p>
</blockquote>
          <p><a href="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/9">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/9</link>
        <pubDate>Mon, 23 Aug 2021 15:38:15 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-8943-9</guid>
        <source url="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943.rss">Redashv8 cant connect to mysql8</source>
      </item>
      <item>
        <title>Redashv8 cant connect to mysql8</title>
        <dc:creator><![CDATA[hananv]]></dc:creator>
        <description><![CDATA[
            <p>some updates</p>
<ol>
<li>i update again the mysqlclient-2.0.3 at the entire workers , stop the docker and up them again and mysqlv5 works ok but mysqlv8 still have the same error</li>
<li>i tried to run python on the same VM with the following command<br>
2.1) import MySQLdb<br>
db=MySQLdb.connect(host = “host”, user = “user”,passwd=“pass”,db=“db”)<br>
and it success<br>
2.2) when i enter redash worker and run the same command at python cli it fail with the same issue , Plugin caching_sha2_password could not be loaded</li>
<li>so it looks it related to the mysqlclient at python-alpine<br>
3.1) see this <a href="https://github.com/PyMySQL/mysqlclient/issues/442" class="inline-onebox" rel="noopener nofollow ugc">New MySQL 8 Default Authentication Plugin Not Supported · Issue #442 · PyMySQL/mysqlclient · GitHub</a>
</li>
</ol>
          <p><a href="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/8">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/8</link>
        <pubDate>Mon, 23 Aug 2021 13:10:37 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-8943-8</guid>
        <source url="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943.rss">Redashv8 cant connect to mysql8</source>
      </item>
      <item>
        <title>Redashv8 cant connect to mysql8</title>
        <dc:creator><![CDATA[hananv]]></dc:creator>
        <description><![CDATA[
            <p>some next steps</p>
<ol>
<li>i upgrade redash to 10.0.0-beta.b49597 and i get the same error with and without MYSQL_DEFAULT_AUTH=mysql_native_password</li>
<li>i enter to docker redash_adhoc_worker_1 and notice this<br>
2.1) the python is python 3 unlike RedashV8<br>
2.2) the sql libs are<br>
root@9f4a96f318e5:/app# cat requirements_all_ds.txt  | grep sql<br>
mysqlclient==1.3.14<br>
pymssql==2.1.4<br>
memsql==3.0.0</li>
</ol>
<p>2.3) when i tried to update mysqlclient</p>
<p>pip install mysqlclient --upgrade<br>
Collecting mysqlclient<br>
Downloading mysqlclient-2.0.3.tar.gz (88 kB)<br>
|████████████████████████████████| 88 kB 1.1 MB/s<br>
Building wheels for collected packages: mysqlclient<br>
Building wheel for mysqlclient (setup.py) … done<br>
Created wheel for mysqlclient: filename=mysqlclient-2.0.3-cp37-cp37m-linux_x86_64.whl size=56883 sha256=87c3df73b361556b0bcb05e5c988a362b8b9f6f405166f3e1c3fa5c1f7851b70<br>
Stored in directory: /tmp/pip-ephem-wheel-cache-yyt7dssj/wheels/79/1c/f8/11fafab45fe6696eea63794a5d747b9c6b54990ac6f1885fb7<br>
Successfully built mysqlclient<br>
Installing collected packages: mysqlclient<br>
Attempting uninstall: mysqlclient<br>
Found existing installation: mysqlclient 1.3.14<br>
Uninstalling mysqlclient-1.3.14:<br>
Successfully uninstalled mysqlclient-1.3.14<br>
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.</p>
<p>We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.</p>
<p>memsql 3.0.0 requires mysqlclient==1.3.13, but you’ll have mysqlclient 2.0.3 which is incompatible.<br>
Successfully installed mysqlclient-2.0.3</p>
<p>2.4) now i get error that “connect() ‘charset’ is an invalid keyword argument” for any mysql server i try to connect also to mysqlv5</p>
<p>2.5) i downgrade again mysqlclient==1.3.14 and now i return to the first problem again with mysqlv8 (mysqlv5 works)</p>
<ol start="3">
<li>i want a solution at the client side and not at the mysql server side with user that use old format of password</li>
</ol>
          <p><a href="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/7">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/7</link>
        <pubDate>Thu, 19 Aug 2021 11:27:20 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-8943-7</guid>
        <source url="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943.rss">Redashv8 cant connect to mysql8</source>
      </item>
      <item>
        <title>Redashv8 cant connect to mysql8</title>
        <dc:creator><![CDATA[jesse]]></dc:creator>
        <description><![CDATA[
            <p>Sounds like an issue with your mysql instance then. Perhaps <a href="https://stackoverflow.com/questions/49194719/authentication-plugin-caching-sha2-password-cannot-be-loaded">this SO question</a> or a google search will help you.</p>
          <p><a href="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/6">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/6</link>
        <pubDate>Tue, 17 Aug 2021 14:07:07 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-8943-6</guid>
        <source url="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943.rss">Redashv8 cant connect to mysql8</source>
      </item>
      <item>
        <title>Redashv8 cant connect to mysql8</title>
        <dc:creator><![CDATA[hananv]]></dc:creator>
        <description><![CDATA[
            <p>i have upgrade mysqlclient to 1.4.6<br>
at<br>
redash_scheduled_worker_1<br>
redash_scheduler_1<br>
redash_adhoc_worker_1<br>
redash_server_1</p>
<p>then docker-compose stop<br>
docker-compose up -d</p>
<p>but it still return the same error</p>
          <p><a href="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/5">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/5</link>
        <pubDate>Tue, 17 Aug 2021 10:20:05 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-8943-5</guid>
        <source url="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943.rss">Redashv8 cant connect to mysql8</source>
      </item>
      <item>
        <title>Redashv8 cant connect to mysql8</title>
        <dc:creator><![CDATA[jesse]]></dc:creator>
        <description><![CDATA[
            <p>You at least need to update the workers as well. The <code>server</code> never communicates with your database.</p>
<p>I’ve not seen any issue reports about the V10 beta.</p>
          <p><a href="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/4">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/4</link>
        <pubDate>Tue, 17 Aug 2021 00:46:35 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-8943-4</guid>
        <source url="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943.rss">Redashv8 cant connect to mysql8</source>
      </item>
      <item>
        <title>Redashv8 cant connect to mysql8</title>
        <dc:creator><![CDATA[hananv]]></dc:creator>
        <description><![CDATA[
            <p>Yes at redash_server_1<br>
should i do it at other services as well ?</p>
<p>does upgrading to Redash v10 can solve also the problem ?</p>
          <p><a href="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/3">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/3</link>
        <pubDate>Mon, 16 Aug 2021 22:50:02 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-8943-3</guid>
        <source url="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943.rss">Redashv8 cant connect to mysql8</source>
      </item>
      <item>
        <title>Redashv8 cant connect to mysql8</title>
        <dc:creator><![CDATA[jesse]]></dc:creator>
        <description><![CDATA[
            <p>Did you update your <code>mysqlclient</code> to <code>1.4.6</code> or higher?</p>
          <p><a href="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/2">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/2</link>
        <pubDate>Mon, 16 Aug 2021 14:38:22 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-8943-2</guid>
        <source url="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943.rss">Redashv8 cant connect to mysql8</source>
      </item>
      <item>
        <title>Redashv8 cant connect to mysql8</title>
        <dc:creator><![CDATA[hananv]]></dc:creator>
        <description><![CDATA[
            <p>Hi ,</p>
<p>i have use RedashV8 on premise install via docker on  Ubuntu 18.04.4 and it works very good with mysqlv5<br>
We have to upgrade mysql to V8 and we start to see issues with the connection<br>
it return<br>
“Connection Test Failed:<br>
(2059, ‘Plugin caching_sha2_password could not be loaded: /usr/lib/x86_64-linux-gnu/mariadb19/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory’”</p>
<p>i saw these two discuss</p><aside class="quote quote-modified" data-post="1" data-topic="6328">
  <div class="title">
    <div class="quote-controls"></div>
    <img loading="lazy" alt="" width="20" height="20" src="https://sjc6.discourse-cdn.com/standard17/user_avatar/discuss.redash.io/mmiyahara/40/2100_2.png" class="avatar">
    <a href="http://discuss.redash.io/t/cant-connect-mysql-to-redash-v8/6328">Can't connect MySQL to Redash v8</a> <a class="badge-wrapper  bullet" href="https://discuss.redash.io/c/support/support-self-hosted/9"><span class="badge-category-parent-bg" style="background-color: #BF1E2E;"></span><span class="badge-category-bg" style="background-color: #AB9364;"></span><span style="" data-drop-close="true" class="badge-category clear-badge" title="Support on installing, configuring and troubleshooting issues with self hosted Redash.">Self Hosted Redash Support</span></a>
  </div>
  <blockquote>
    Issue Summary
After upgrading Redash v7 to v8, I have an issue where I cannot connect MySQL to Redash with the following error. 

Plugin caching_sha2_password could not be loaded: /usr/lib/x86_64-linux-gnu/mariadb19/plugin/caching_sha2_password.so 

It seems like this problem is caused by the MySQL user’s authentication type “caching_sha2_password”. 
So I created a new user with the type “mysql_native_password” and try to connect again, which ended up with the following error. 

Plugin sha256_pa…
  </blockquote>
</aside>
<aside class="quote quote-modified" data-post="1" data-topic="4118">
  <div class="title">
    <div class="quote-controls"></div>
    <img loading="lazy" alt="" width="20" height="20" src="https://avatars.discourse-cdn.com/v4/letter/d/c68b51/40.png" class="avatar">
    <a href="http://discuss.redash.io/t/connection-test-failed-mysql/4118">Connection Test Failed mysql</a> <a class="badge-wrapper  bullet" href="https://discuss.redash.io/c/support/support-self-hosted/9"><span class="badge-category-parent-bg" style="background-color: #BF1E2E;"></span><span class="badge-category-bg" style="background-color: #AB9364;"></span><span style="" data-drop-close="true" class="badge-category clear-badge" title="Support on installing, configuring and troubleshooting issues with self hosted Redash.">Self Hosted Redash Support</span></a>
  </div>
  <blockquote>
    Issue Summary
I try to connect to remote mysql data base (version: 8.0.16) but an error is returned. 
I connected to this data base in a previous version without problem. 
[Screenshot%20from%202019-07-05%2018%3A22%3A25] 
Technical details:

Redash Version:8.0.0-beta (dev)
Browser/OS: google chrome / linux
How did you install Redash: docker
  </blockquote>
</aside>

<p>and i have add<br>
MYSQL_DEFAULT_AUTH=mysql_native_password to env<br>
but it is also do not solve the issue</p>
<p>do you have another suggestion at the client side and not change the password plugin at the mysql side ?</p>
          <p><a href="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/1">Read full topic</a></p>
        ]]></description>
        <link>https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943/1</link>
        <pubDate>Mon, 16 Aug 2021 13:31:17 +0000</pubDate>
        <guid isPermaLink="false">discuss.redash.io-post-8943-1</guid>
        <source url="https://discuss.redash.io/t/redashv8-cant-connect-to-mysql8/8943.rss">Redashv8 cant connect to mysql8</source>
      </item>
  </channel>
</rss>
